// Mapeamento completo de Item IDs para nomes e URLs de imagens
// Baseado nos dados do OpenDota/Dota 2 Constants
// Auto-generated + manual enhancements

export interface ItemInfo {
  id: number;
  name: string;
  displayName: string;
  image: string;
  cost?: number;
  description?: string;
  stats?: string[];
}

const ITEM_BASE_URL = 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/items';

export const ITEMS_MAP: { [key: number]: ItemInfo} = {
  1: { id: 1, name: 'blink', displayName: 'Blink', image: `${ITEM_BASE_URL}/blink.png`, cost: 2250, description: 'Ativa: Teleporta até 1200 unidades. Não pode ser usado por 3s após receber dano de jogador.' },
  2: { id: 2, name: 'blades_of_attack', displayName: 'Blades Of Attack', image: `${ITEM_BASE_URL}/blades_of_attack.png`, cost: 450 },
  3: { id: 3, name: 'broadsword', displayName: 'Broadsword', image: `${ITEM_BASE_URL}/broadsword.png`, cost: 1000 },
  4: { id: 4, name: 'chainmail', displayName: 'Chainmail', image: `${ITEM_BASE_URL}/chainmail.png`, cost: 550 },
  5: { id: 5, name: 'claymore', displayName: 'Claymore', image: `${ITEM_BASE_URL}/claymore.png`, cost: 1350 },
  6: { id: 6, name: 'helm_of_iron_will', displayName: 'Helm Of Iron Will', image: `${ITEM_BASE_URL}/helm_of_iron_will.png`, cost: 975 },
  7: { id: 7, name: 'javelin', displayName: 'Javelin', image: `${ITEM_BASE_URL}/javelin.png`, cost: 900 },
  8: { id: 8, name: 'mithril_hammer', displayName: 'Mithril Hammer', image: `${ITEM_BASE_URL}/mithril_hammer.png`, cost: 1600 },
  9: { id: 9, name: 'platemail', displayName: 'Platemail', image: `${ITEM_BASE_URL}/platemail.png`, cost: 1400 },
  10: { id: 10, name: 'quarterstaff', displayName: 'Quarterstaff', image: `${ITEM_BASE_URL}/quarterstaff.png`, cost: 875 },
  11: { id: 11, name: 'quelling_blade', displayName: 'Quelling Blade', image: `${ITEM_BASE_URL}/quelling_blade.png`, cost: 100 },
  12: { id: 12, name: 'ring_of_protection', displayName: 'Ring Of Protection', image: `${ITEM_BASE_URL}/ring_of_protection.png`, cost: 175 },
  13: { id: 13, name: 'gauntlets', displayName: 'Gauntlets of Strength', image: `${ITEM_BASE_URL}/gauntlets.png`, cost: 140 },
  14: { id: 14, name: 'slippers', displayName: 'Slippers of Agility', image: `${ITEM_BASE_URL}/slippers.png`, cost: 140 },
  15: { id: 15, name: 'mantle', displayName: 'Mantle of Intelligence', image: `${ITEM_BASE_URL}/mantle.png`, cost: 140 },
  16: { id: 16, name: 'branches', displayName: 'Iron Branch', image: `${ITEM_BASE_URL}/branches.png`, cost: 50 },
  17: { id: 17, name: 'belt_of_strength', displayName: 'Belt Of Strength', image: `${ITEM_BASE_URL}/belt_of_strength.png`, cost: 450 },
  18: { id: 18, name: 'boots_of_elves', displayName: 'Boots Of Elves', image: `${ITEM_BASE_URL}/boots_of_elves.png`, cost: 450 },
  19: { id: 19, name: 'robe', displayName: 'Robe', image: `${ITEM_BASE_URL}/robe.png`, cost: 450 },
  20: { id: 20, name: 'circlet', displayName: 'Circlet', image: `${ITEM_BASE_URL}/circlet.png`, cost: 155 },
  21: { id: 21, name: 'ogre_axe', displayName: 'Ogre Axe', image: `${ITEM_BASE_URL}/ogre_axe.png`, cost: 1000 },
  22: { id: 22, name: 'blade_of_alacrity', displayName: 'Blade Of Alacrity', image: `${ITEM_BASE_URL}/blade_of_alacrity.png`, cost: 1000 },
  23: { id: 23, name: 'staff_of_wizardry', displayName: 'Staff Of Wizardry', image: `${ITEM_BASE_URL}/staff_of_wizardry.png`, cost: 1000 },
  24: { id: 24, name: 'ultimate_orb', displayName: 'Ultimate Orb', image: `${ITEM_BASE_URL}/ultimate_orb.png`, cost: 2800 },
  25: { id: 25, name: 'gloves', displayName: 'Gloves', image: `${ITEM_BASE_URL}/gloves.png`, cost: 450 },
  26: { id: 26, name: 'lifesteal', displayName: 'Morbid Mask', image: `${ITEM_BASE_URL}/lifesteal.png`, cost: 900 },
  27: { id: 27, name: 'ring_of_regen', displayName: 'Ring Of Regen', image: `${ITEM_BASE_URL}/ring_of_regen.png`, cost: 175 },
  28: { id: 28, name: 'sobi_mask', displayName: 'Sobi Mask', image: `${ITEM_BASE_URL}/sobi_mask.png`, cost: 175 },
  29: { id: 29, name: 'boots', displayName: 'Boots of Speed', image: `${ITEM_BASE_URL}/boots.png`, cost: 500, stats: ['+45 Velocidade de Movimento'], description: 'Botas básicas de velocidade.' },
  30: { id: 30, name: 'gem', displayName: 'Gem', image: `${ITEM_BASE_URL}/gem.png`, cost: 900 },
  31: { id: 31, name: 'cloak', displayName: 'Cloak', image: `${ITEM_BASE_URL}/cloak.png`, cost: 800 },
  32: { id: 32, name: 'talisman_of_evasion', displayName: 'Talisman Of Evasion', image: `${ITEM_BASE_URL}/talisman_of_evasion.png`, cost: 1300 },
  33: { id: 33, name: 'cheese', displayName: 'Cheese', image: `${ITEM_BASE_URL}/cheese.png`, cost: 1000, description: 'Restaura 2500 vida e 1500 mana instantaneamente. Dropa de Roshan.' },
  34: { id: 34, name: 'magic_stick', displayName: 'Magic Stick', image: `${ITEM_BASE_URL}/magic_stick.png`, cost: 200, description: 'Ganha cargas com spells inimigas. Ativa: +15 vida/mana por carga.' },
  36: { id: 36, name: 'magic_wand', displayName: 'Magic Wand', image: `${ITEM_BASE_URL}/magic_wand.png`, cost: 450, stats: ['+3 Todos Atributos'], description: 'Ganha cargas com spells inimigas. Ativa: +15 vida/mana por carga.' },
  37: { id: 37, name: 'ghost', displayName: 'Ghost Scepter', image: `${ITEM_BASE_URL}/ghost.png`, cost: 1500 },
  38: { id: 38, name: 'clarity', displayName: 'Clarity', image: `${ITEM_BASE_URL}/clarity.png`, cost: 50, description: 'Regenera 6 mana/s por 25s. Quebra ao tomar dano.' },
  39: { id: 39, name: 'flask', displayName: 'Healing Salve', image: `${ITEM_BASE_URL}/flask.png`, cost: 100, description: 'Regenera 14 vida/s e 2 mana/s por 12s.' },
  40: { id: 40, name: 'dust', displayName: 'Dust of Appearance', image: `${ITEM_BASE_URL}/dust.png`, cost: 80, description: 'Revela unidades invisíveis em área por 12s.' },
  41: { id: 41, name: 'bottle', displayName: 'Bottle', image: `${ITEM_BASE_URL}/bottle.png`, cost: 675 },
  42: { id: 42, name: 'ward_observer', displayName: 'Ward Observer', image: `${ITEM_BASE_URL}/ward_observer.png`, description: 'Fornece visão em área. Dura 6 minutos.' },
  43: { id: 43, name: 'ward_sentry', displayName: 'Ward Sentry', image: `${ITEM_BASE_URL}/ward_sentry.png`, cost: 50, description: 'Fornece True Sight em área. Dura 7 minutos.' },
  44: { id: 44, name: 'tango', displayName: 'Tango', image: `${ITEM_BASE_URL}/tango.png`, cost: 90, description: 'Come uma árvore para regenerar 7% da vida máxima por 16s.' },
  45: { id: 45, name: 'courier', displayName: 'Courier', image: `${ITEM_BASE_URL}/courier.png`, cost: 50 },
  46: { id: 46, name: 'tpscroll', displayName: 'Town Portal Scroll', image: `${ITEM_BASE_URL}/tpscroll.png`, cost: 100, description: 'Teleporta para edificação aliada após 3s de canalização.' },
  48: { id: 48, name: 'travel_boots', displayName: 'Travel Boots', image: `${ITEM_BASE_URL}/travel_boots.png`, cost: 2500, stats: ['+115 Velocidade'], description: 'Ativa: Teleporta para aliado, creep ou edificação.' },
  50: { id: 50, name: 'phase_boots', displayName: 'Phase Boots', image: `${ITEM_BASE_URL}/phase_boots.png`, cost: 1500, stats: ['+45 Velocidade', '+18 Dano'], description: 'Fase: +20% velocidade e atravessa unidades por 3s.' },
  51: { id: 51, name: 'demon_edge', displayName: 'Demon Edge', image: `${ITEM_BASE_URL}/demon_edge.png`, cost: 2200 },
  52: { id: 52, name: 'eagle', displayName: 'Eagle', image: `${ITEM_BASE_URL}/eagle.png`, cost: 2800 },
  53: { id: 53, name: 'reaver', displayName: 'Reaver', image: `${ITEM_BASE_URL}/reaver.png`, cost: 2800 },
  54: { id: 54, name: 'relic', displayName: 'Relic', image: `${ITEM_BASE_URL}/relic.png`, cost: 3400 },
  55: { id: 55, name: 'hyperstone', displayName: 'Hyperstone', image: `${ITEM_BASE_URL}/hyperstone.png`, cost: 2000 },
  56: { id: 56, name: 'ring_of_health', displayName: 'Ring Of Health', image: `${ITEM_BASE_URL}/ring_of_health.png`, cost: 700 },
  57: { id: 57, name: 'void_stone', displayName: 'Void Stone', image: `${ITEM_BASE_URL}/void_stone.png`, cost: 700 },
  58: { id: 58, name: 'mystic_staff', displayName: 'Mystic Staff', image: `${ITEM_BASE_URL}/mystic_staff.png`, cost: 2800 },
  59: { id: 59, name: 'energy_booster', displayName: 'Energy Booster', image: `${ITEM_BASE_URL}/energy_booster.png`, cost: 800 },
  60: { id: 60, name: 'point_booster', displayName: 'Point Booster', image: `${ITEM_BASE_URL}/point_booster.png`, cost: 1200 },
  61: { id: 61, name: 'vitality_booster', displayName: 'Vitality Booster', image: `${ITEM_BASE_URL}/vitality_booster.png`, cost: 1000 },
  63: { id: 63, name: 'power_treads', displayName: 'Power Treads', image: `${ITEM_BASE_URL}/power_treads.png`, cost: 1400, stats: ['+45 Velocidade', '+25 Velocidade de Ataque'], description: 'Ativa: Alterna entre +10 Força/Agilidade/Inteligência.' },
  65: { id: 65, name: 'hand_of_midas', displayName: 'Hand Of Midas', image: `${ITEM_BASE_URL}/hand_of_midas.png`, cost: 2200 },
  67: { id: 67, name: 'oblivion_staff', displayName: 'Oblivion Staff', image: `${ITEM_BASE_URL}/oblivion_staff.png`, cost: 1625 },
  69: { id: 69, name: 'pers', displayName: 'Pers', image: `${ITEM_BASE_URL}/pers.png`, cost: 1400 },
  71: { id: 71, name: 'poor_mans_shield', displayName: 'Poor Mans Shield', image: `${ITEM_BASE_URL}/poor_mans_shield.png` },
  73: { id: 73, name: 'bracer', displayName: 'Bracer', image: `${ITEM_BASE_URL}/bracer.png`, cost: 505, stats: ['+6 Força', '+3 Agilidade/Inteligência', '+0.75 HP Regen'], description: 'Item early game de atributos e sustain.' },
  75: { id: 75, name: 'wraith_band', displayName: 'Wraith Band', image: `${ITEM_BASE_URL}/wraith_band.png`, cost: 505, stats: ['+6 Agilidade', '+3 Força/Inteligência', '+0.5 Armadura'], description: 'Item early game para heróis de agilidade.' },
  77: { id: 77, name: 'null_talisman', displayName: 'Null Talisman', image: `${ITEM_BASE_URL}/null_talisman.png`, cost: 505, stats: ['+6 Inteligência', '+3 Força/Agilidade', '+0.75 Mana Regen'], description: 'Item early game para heróis de inteligência.' },
  79: { id: 79, name: 'mekansm', displayName: 'Mekansm', image: `${ITEM_BASE_URL}/mekansm.png`, cost: 1775 },
  81: { id: 81, name: 'vladmir', displayName: 'Vladmir', image: `${ITEM_BASE_URL}/vladmir.png`, cost: 2200, stats: ['+2 Mana Regen', '+18% Roubo de Vida'], description: 'Aura: Roubo de vida, armadura, dano e mana regen para aliados.' },
  86: { id: 86, name: 'buckler', displayName: 'Buckler', image: `${ITEM_BASE_URL}/buckler.png`, cost: 425 },
  88: { id: 88, name: 'ring_of_basilius', displayName: 'Ring Of Basilius', image: `${ITEM_BASE_URL}/ring_of_basilius.png`, cost: 425 },
  90: { id: 90, name: 'pipe', displayName: 'Pipe', image: `${ITEM_BASE_URL}/pipe.png`, cost: 3725, stats: ['+8.5 HP Regen', '+30% Resistência Mágica'], description: 'Barreira: 400 escudo mágico em área por 12s.' },
  92: { id: 92, name: 'urn_of_shadows', displayName: 'Urn Of Shadows', image: `${ITEM_BASE_URL}/urn_of_shadows.png`, cost: 825, stats: ['+2 Força', '+0.75 Mana Regen'], description: 'Ganha cargas com kills. Cura aliados ou causa dano em inimigos.' },
  94: { id: 94, name: 'headdress', displayName: 'Headdress', image: `${ITEM_BASE_URL}/headdress.png`, cost: 425 },
  96: { id: 96, name: 'sheepstick', displayName: 'Sheepstick', image: `${ITEM_BASE_URL}/sheepstick.png`, cost: 5200, stats: ['+35 Inteligência', '+10 Todos Atributos'], description: 'Hex: Transforma inimigo em criatura inofensiva por 3.5s.' },
  98: { id: 98, name: 'orchid', displayName: 'Orchid', image: `${ITEM_BASE_URL}/orchid.png`, cost: 3275, stats: ['+30 Inteligência', '+30 Velocidade de Ataque', '+3 Mana Regen'], description: 'Silêncio: Silencia e amplifica 30% do dano por 5s.' },
  100: { id: 100, name: 'cyclone', displayName: 'Cyclone', image: `${ITEM_BASE_URL}/cyclone.png`, cost: 2600 },
  102: { id: 102, name: 'force_staff', displayName: 'Force Staff', image: `${ITEM_BASE_URL}/force_staff.png`, cost: 2200, stats: ['+15 Inteligência', '+2 HP Regen'], description: 'Força: Empurra você ou aliado 600 unidades.' },
  104: { id: 104, name: 'dagon', displayName: 'Dagon', image: `${ITEM_BASE_URL}/dagon.png`, cost: 2850 },
  106: { id: 106, name: 'necronomicon', displayName: 'Necronomicon', image: `${ITEM_BASE_URL}/necronomicon.png`, cost: 2050 },
  108: { id: 108, name: 'ultimate_scepter', displayName: 'Aghanim\'s Scepter', image: `${ITEM_BASE_URL}/ultimate_scepter.png`, cost: 4200, stats: ['+10 Todos Atributos', '+175 Vida', '+175 Mana'], description: 'Melhora ou adiciona uma habilidade ultimate do herói.' },
  110: { id: 110, name: 'refresher', displayName: 'Refresher', image: `${ITEM_BASE_URL}/refresher.png`, cost: 5000, stats: ['+12 HP Regen', '+5 Mana Regen'], description: 'Reseta todos cooldowns e restaura 375 vida e mana.' },
  112: { id: 112, name: 'assault', displayName: 'Assault', image: `${ITEM_BASE_URL}/assault.png`, cost: 5125, stats: ['+30 Velocidade Ataque', '+10 Armadura'], description: 'Aura: +5 armadura aliados, -5 armadura inimigos.' },
  114: { id: 114, name: 'heart', displayName: 'Heart', image: `${ITEM_BASE_URL}/heart.png`, cost: 5200, stats: ['+45 Força', '+250 Vida'], description: 'Regenera 6% da vida máxima por segundo fora de combate.' },
  116: { id: 116, name: 'black_king_bar', displayName: 'Black King Bar', image: `${ITEM_BASE_URL}/black_king_bar.png`, cost: 4050, stats: ['+24 Dano', '+10 Força'], description: 'Avatar: Te torna imune a magia por 9-6s (diminui a cada uso).' },
  117: { id: 117, name: 'aegis', displayName: 'Aegis', image: `${ITEM_BASE_URL}/aegis.png`, description: 'Revive no local da morte com 100% vida/mana. Dura 5min.' },
  119: { id: 119, name: 'shivas_guard', displayName: 'Shivas Guard', image: `${ITEM_BASE_URL}/shivas_guard.png`, cost: 5175, stats: ['+15 Inteligência', '+15 Armadura', '+4 HP Regen'], description: 'Explosão de Gelo: 350 dano em área e reduz velocidade de ataque.' },
  121: { id: 121, name: 'bloodstone', displayName: 'Bloodstone', image: `${ITEM_BASE_URL}/bloodstone.png`, cost: 4400, stats: ['+18 Inteligência', '+500 Vida', '+400 Mana'], description: 'Ganha cargas com kills. Reduz cooldowns e aumenta mana regen.' },
  123: { id: 123, name: 'sphere', displayName: 'Sphere', image: `${ITEM_BASE_URL}/sphere.png`, cost: 4800, stats: ['+15 Todos Atributos', '+6 HP Regen', '+5 Mana Regen'], description: 'Bloqueia uma spell alvo a cada 12s.' },
  125: { id: 125, name: 'vanguard', displayName: 'Vanguard', image: `${ITEM_BASE_URL}/vanguard.png`, cost: 1700, stats: ['+8 HP Regen', '+250 Vida'], description: 'Bloqueia 70 dano de ataques (35 se ranged).' },
  127: { id: 127, name: 'blade_mail', displayName: 'Blade Mail', image: `${ITEM_BASE_URL}/blade_mail.png`, cost: 2300, stats: ['+28 Dano', '+6 Armadura', '+6 Inteligência'], description: 'Reflete 100% do dano recebido antes de redução.' },
  129: { id: 129, name: 'soul_booster', displayName: 'Soul Booster', image: `${ITEM_BASE_URL}/soul_booster.png`, cost: 3000 },
  131: { id: 131, name: 'hood_of_defiance', displayName: 'Hood Of Defiance', image: `${ITEM_BASE_URL}/hood_of_defiance.png` },
  133: { id: 133, name: 'rapier', displayName: 'Rapier', image: `${ITEM_BASE_URL}/rapier.png`, cost: 5600, stats: ['+350 Dano'], description: 'CUIDADO: Dropa ao morrer e pode ser pego por inimigos!' },
  135: { id: 135, name: 'monkey_king_bar', displayName: 'Monkey King Bar', image: `${ITEM_BASE_URL}/monkey_king_bar.png`, cost: 4700, stats: ['+45 Dano', '+45 Velocidade de Ataque'], description: 'Pierce: 75% chance de 70 dano mágico extra. Ignora evasão.' },
  137: { id: 137, name: 'radiance', displayName: 'Radiance', image: `${ITEM_BASE_URL}/radiance.png`, cost: 4700, stats: ['+65 Dano'], description: 'Queima 60 dano/s em área. 17% chance de errar ataques.' },
  139: { id: 139, name: 'butterfly', displayName: 'Butterfly', image: `${ITEM_BASE_URL}/butterfly.png`, cost: 5450, stats: ['+35 Agilidade', '+35 Velocidade de Ataque', '+35% Evasão'], description: 'Flutter: +35 velocidade e 35% evasão.' },
  141: { id: 141, name: 'greater_crit', displayName: 'Greater Crit', image: `${ITEM_BASE_URL}/greater_crit.png`, cost: 5100 },
  143: { id: 143, name: 'basher', displayName: 'Basher', image: `${ITEM_BASE_URL}/basher.png`, cost: 2875 },
  145: { id: 145, name: 'bfury', displayName: 'Bfury', image: `${ITEM_BASE_URL}/bfury.png`, cost: 3900 },
  147: { id: 147, name: 'manta', displayName: 'Manta', image: `${ITEM_BASE_URL}/manta.png`, cost: 4650, stats: ['+26 Agilidade', '+12 Força/Int', '+12% Velocidade'], description: 'Cria 2 ilusões que causam 33% do dano (28% ranged).' },
  149: { id: 149, name: 'lesser_crit', displayName: 'Lesser Crit', image: `${ITEM_BASE_URL}/lesser_crit.png`, cost: 2000 },
  151: { id: 151, name: 'armlet', displayName: 'Armlet', image: `${ITEM_BASE_URL}/armlet.png`, cost: 2500, stats: ['+25 Velocidade de Ataque', '+7 HP Regen'], description: 'Ativa: +31 dano, +25 força, mas drena 54 vida/s.' },
  152: { id: 152, name: 'invis_sword', displayName: 'Invis Sword', image: `${ITEM_BASE_URL}/invis_sword.png`, cost: 3350 },
  154: { id: 154, name: 'sange_and_yasha', displayName: 'Sange And Yasha', image: `${ITEM_BASE_URL}/sange_and_yasha.png`, cost: 4200, stats: ['+16 Força/Agilidade', '+16% Velocidade'], description: 'Maim: Retarda inimigos. Aumenta velocidade e status resistance.' },
  156: { id: 156, name: 'satanic', displayName: 'Satanic', image: `${ITEM_BASE_URL}/satanic.png`, cost: 5050, stats: ['+25 Força', '+55 Dano', '+25% Roubo de Vida'], description: 'Profano: 200% roubo de vida por 5s.' },
  158: { id: 158, name: 'mjollnir', displayName: 'Mjollnir', image: `${ITEM_BASE_URL}/mjollnir.png`, cost: 5500, stats: ['+70 Velocidade de Ataque', '+24 Dano'], description: 'Corrente de raio em ataques. Ativa: Escudo estático.' },
  160: { id: 160, name: 'skadi', displayName: 'Skadi', image: `${ITEM_BASE_URL}/skadi.png`, cost: 5900 },
  162: { id: 162, name: 'sange', displayName: 'Sange', image: `${ITEM_BASE_URL}/sange.png`, cost: 2100, stats: ['+16 Força', '+16% Amplificação Lifesteal'], description: 'Maim: Retarda movimento e reduz cura.' },
  164: { id: 164, name: 'helm_of_the_dominator', displayName: 'Helm Of The Dominator', image: `${ITEM_BASE_URL}/helm_of_the_dominator.png`, cost: 2550 },
  166: { id: 166, name: 'maelstrom', displayName: 'Maelstrom', image: `${ITEM_BASE_URL}/maelstrom.png`, cost: 2950, stats: ['+25 Dano', '+25 Velocidade de Ataque'], description: 'Corrente: 30% chance de 140 dano mágico em área.' },
  168: { id: 168, name: 'desolator', displayName: 'Desolator', image: `${ITEM_BASE_URL}/desolator.png`, cost: 3500, stats: ['+60 Dano'], description: 'Corrosão: -6 de armadura por 7s.' },
  170: { id: 170, name: 'yasha', displayName: 'Yasha', image: `${ITEM_BASE_URL}/yasha.png`, cost: 2100, stats: ['+16 Agilidade', '+16% Velocidade'], description: 'Aumenta velocidade de movimento e ataque.' },
  172: { id: 172, name: 'mask_of_madness', displayName: 'Mask Of Madness', image: `${ITEM_BASE_URL}/mask_of_madness.png`, cost: 1900, stats: ['+20 Dano', '+20% Roubo de Vida'], description: 'Berserk: +110 velocidade de ataque mas toma +30% dano.' },
  174: { id: 174, name: 'diffusal_blade', displayName: 'Diffusal Blade', image: `${ITEM_BASE_URL}/diffusal_blade.png`, cost: 2500, stats: ['+25 Agilidade', '+15 Inteligência'], description: 'Queima 50 mana e retarda inimigos. Purga buffs.' },
  176: { id: 176, name: 'ethereal_blade', displayName: 'Ethereal Blade', image: `${ITEM_BASE_URL}/ethereal_blade.png`, cost: 5375, stats: ['+40 Agilidade/Inteligência', '+10 Todos Atributos'], description: 'Torna alvo etéreo: +40% dano mágico, imune a físico.' },
  178: { id: 178, name: 'soul_ring', displayName: 'Soul Ring', image: `${ITEM_BASE_URL}/soul_ring.png`, cost: 805, stats: ['+2 HP Regen', '+1.25 Mana Regen'], description: 'Sacrifica 170 vida para ganhar 250 mana temporária.' },
  180: { id: 180, name: 'arcane_boots', displayName: 'Arcane Boots', image: `${ITEM_BASE_URL}/arcane_boots.png`, cost: 1400, stats: ['+45 Velocidade', '+250 Mana'], description: 'Regeneração em Área: Restaura 175 mana em área.' },
  181: { id: 181, name: 'orb_of_venom', displayName: 'Orb Of Venom', image: `${ITEM_BASE_URL}/orb_of_venom.png`, cost: 350 },
  182: { id: 182, name: 'stout_shield', displayName: 'Stout Shield', image: `${ITEM_BASE_URL}/stout_shield.png`, cost: 100 },
  185: { id: 185, name: 'ancient_janggo', displayName: 'Ancient Janggo', image: `${ITEM_BASE_URL}/ancient_janggo.png`, cost: 1625 },
  187: { id: 187, name: 'medallion_of_courage', displayName: 'Medallion Of Courage', image: `${ITEM_BASE_URL}/medallion_of_courage.png`, cost: 1025 },
  188: { id: 188, name: 'smoke_of_deceit', displayName: 'Smoke Of Deceit', image: `${ITEM_BASE_URL}/smoke_of_deceit.png`, cost: 50, description: 'Invisibilidade e +15% velocidade em área. Quebra próximo de inimigos.' },
  190: { id: 190, name: 'veil_of_discord', displayName: 'Veil Of Discord', image: `${ITEM_BASE_URL}/veil_of_discord.png`, cost: 1725 },
  193: { id: 193, name: 'necronomicon_2', displayName: 'Necronomicon 2', image: `${ITEM_BASE_URL}/necronomicon_2.png`, cost: 3300 },
  194: { id: 194, name: 'necronomicon_3', displayName: 'Necronomicon 3', image: `${ITEM_BASE_URL}/necronomicon_3.png`, cost: 4550 },
  196: { id: 196, name: 'diffusal_blade_2', displayName: 'Diffusal Blade 2', image: `${ITEM_BASE_URL}/diffusal_blade_2.png`, cost: 3850 },
  201: { id: 201, name: 'dagon_2', displayName: 'Dagon 2', image: `${ITEM_BASE_URL}/dagon_2.png`, cost: 4000 },
  202: { id: 202, name: 'dagon_3', displayName: 'Dagon 3', image: `${ITEM_BASE_URL}/dagon_3.png`, cost: 5150 },
  203: { id: 203, name: 'dagon_4', displayName: 'Dagon 4', image: `${ITEM_BASE_URL}/dagon_4.png`, cost: 6300 },
  204: { id: 204, name: 'dagon_5', displayName: 'Dagon 5', image: `${ITEM_BASE_URL}/dagon_5.png`, cost: 7450 },
  206: { id: 206, name: 'rod_of_atos', displayName: 'Rod Of Atos', image: `${ITEM_BASE_URL}/rod_of_atos.png`, cost: 2250 },
  208: { id: 208, name: 'abyssal_blade', displayName: 'Abyssal Blade', image: `${ITEM_BASE_URL}/abyssal_blade.png`, cost: 6250, stats: ['+25 Força', '+10 Dano', '+10 HP Regen'], description: 'Stun: 2s de stun penetrante (atravessa BKB).' },
  210: { id: 210, name: 'heavens_halberd', displayName: 'Heavens Halberd', image: `${ITEM_BASE_URL}/heavens_halberd.png`, cost: 2600, stats: ['+20 Força', '+20% Evasão'], description: 'Desarma heróis a distância por 5s (3s em melee).' },
  212: { id: 212, name: 'ring_of_aquila', displayName: 'Ring Of Aquila', image: `${ITEM_BASE_URL}/ring_of_aquila.png` },
  214: { id: 214, name: 'tranquil_boots', displayName: 'Tranquil Boots', image: `${ITEM_BASE_URL}/tranquil_boots.png`, cost: 900, stats: ['+90 Velocidade', '+3.5 HP Regen'], description: 'Regenera rapidamente quando não está em combate.' },
  215: { id: 215, name: 'shadow_amulet', displayName: 'Shadow Amulet', image: `${ITEM_BASE_URL}/shadow_amulet.png`, cost: 1000 },
  216: { id: 216, name: 'enchanted_mango', displayName: 'Enchanted Mango', image: `${ITEM_BASE_URL}/enchanted_mango.png`, cost: 65, stats: ['+0.6 HP Regen'], description: 'Consome para restaurar 125 mana instantaneamente.' },
  218: { id: 218, name: 'ward_dispenser', displayName: 'Ward Dispenser', image: `${ITEM_BASE_URL}/ward_dispenser.png`, cost: 50 },
  220: { id: 220, name: 'travel_boots_2', displayName: 'Travel Boots 2', image: `${ITEM_BASE_URL}/travel_boots_2.png`, cost: 4500 },
  223: { id: 223, name: 'meteor_hammer', displayName: 'Meteor Hammer', image: `${ITEM_BASE_URL}/meteor_hammer.png`, cost: 2850 },
  225: { id: 225, name: 'nullifier', displayName: 'Nullifier', image: `${ITEM_BASE_URL}/nullifier.png`, cost: 4375 },
  226: { id: 226, name: 'lotus_orb', displayName: 'Lotus Orb', image: `${ITEM_BASE_URL}/lotus_orb.png`, cost: 3850, stats: ['+10 Armadura', '+6.5 HP Regen', '+4 Mana Regen'], description: 'Reflete spells alvejados de volta ao lançador por 6s.' },
  229: { id: 229, name: 'solar_crest', displayName: 'Solar Crest', image: `${ITEM_BASE_URL}/solar_crest.png`, cost: 2575, stats: ['+10 Armadura', '+3 HP Regen'], description: 'Reduz 7 armadura e 25% acurácia do inimigo.' },
  231: { id: 231, name: 'guardian_greaves', displayName: 'Guardian Greaves', image: `${ITEM_BASE_URL}/guardian_greaves.png`, cost: 5050, stats: ['+55 Velocidade', '+5 Armadura', '+3 HP Regen'], description: 'Restaura 350 vida e 200 mana em área. Remove debuffs.' },
  232: { id: 232, name: 'aether_lens', displayName: 'Aether Lens', image: `${ITEM_BASE_URL}/aether_lens.png`, cost: 2275 },
  235: { id: 235, name: 'octarine_core', displayName: 'Octarine Core', image: `${ITEM_BASE_URL}/octarine_core.png`, cost: 4800, stats: ['+30 Inteligência', '+400 Vida', '+400 Mana'], description: 'Reduz 25% de todos cooldowns. 25% Spell Lifesteal.' },
  236: { id: 236, name: 'dragon_lance', displayName: 'Dragon Lance', image: `${ITEM_BASE_URL}/dragon_lance.png`, cost: 1900, stats: ['+15 Força', '+15 Agilidade', '+140 Alcance de Ataque'], description: 'Aumenta alcance de ataque (apenas ranged).' },
  237: { id: 237, name: 'faerie_fire', displayName: 'Faerie Fire', image: `${ITEM_BASE_URL}/faerie_fire.png`, cost: 65 },
  239: { id: 239, name: 'iron_talon', displayName: 'Iron Talon', image: `${ITEM_BASE_URL}/iron_talon.png` },
  240: { id: 240, name: 'blight_stone', displayName: 'Blight Stone', image: `${ITEM_BASE_URL}/blight_stone.png`, cost: 300 },
  241: { id: 241, name: 'tango_single', displayName: 'Tango Single', image: `${ITEM_BASE_URL}/tango_single.png`, cost: 30 },
  242: { id: 242, name: 'crimson_guard', displayName: 'Crimson Guard', image: `${ITEM_BASE_URL}/crimson_guard.png`, cost: 3725, stats: ['+12 HP Regen', '+250 Vida'], description: 'Bloqueia 75 dano. Ativa: Escudo de dano em área.' },
  244: { id: 244, name: 'wind_lace', displayName: 'Wind Lace', image: `${ITEM_BASE_URL}/wind_lace.png`, cost: 225 },
  247: { id: 247, name: 'moon_shard', displayName: 'Moon Shard', image: `${ITEM_BASE_URL}/moon_shard.png`, cost: 4000 },
  249: { id: 249, name: 'silver_edge', displayName: 'Silver Edge', image: `${ITEM_BASE_URL}/silver_edge.png`, cost: 5800, stats: ['+52 Dano', '+40 Velocidade de Ataque'], description: 'Quebra habilidades passivas do inimigo por 4s.' },
  250: { id: 250, name: 'bloodthorn', displayName: 'Bloodthorn', image: `${ITEM_BASE_URL}/bloodthorn.png`, cost: 6625, stats: ['+35 Inteligência', '+55 Velocidade de Ataque', '+3.75 Mana Regen'], description: 'Silêncio True Strike: Silencia e causa critical em todos ataques.' },
  252: { id: 252, name: 'echo_sabre', displayName: 'Echo Sabre', image: `${ITEM_BASE_URL}/echo_sabre.png`, cost: 2700, stats: ['+15 Força', '+15 Inteligência', '+15 Dano'], description: 'Ataque duplo: Segundo ataque rápido após o primeiro.' },
  254: { id: 254, name: 'glimmer_cape', displayName: 'Glimmer Cape', image: `${ITEM_BASE_URL}/glimmer_cape.png`, cost: 2150, stats: ['+20% Resistência Mágica'], description: 'Invisibilidade + 50% resistência mágica por 5s.' },
  256: { id: 256, name: 'aeon_disk', displayName: 'Aeon Disk', image: `${ITEM_BASE_URL}/aeon_disk.png`, cost: 3000, stats: ['+350 Vida', '+350 Mana'], description: 'Combo Breaker: Torna invulnerável se vida cair abaixo de 70%.' },
  257: { id: 257, name: 'tome_of_knowledge', displayName: 'Tome Of Knowledge', image: `${ITEM_BASE_URL}/tome_of_knowledge.png`, cost: 75 },
  259: { id: 259, name: 'kaya', displayName: 'Kaya', image: `${ITEM_BASE_URL}/kaya.png`, cost: 2100, stats: ['+16 Inteligência', '+16% Amplificação Spell'], description: 'Aumenta spell damage e reduz mana cost.' },
  260: { id: 260, name: 'refresher_shard', displayName: 'Refresher Shard', image: `${ITEM_BASE_URL}/refresher_shard.png`, cost: 1000 },
  261: { id: 261, name: 'crown', displayName: 'Crown', image: `${ITEM_BASE_URL}/crown.png`, cost: 450 },
  263: { id: 263, name: 'hurricane_pike', displayName: 'Hurricane Pike', image: `${ITEM_BASE_URL}/hurricane_pike.png`, cost: 4450, stats: ['+25 Agilidade', '+15 Força/Int', '+190 Alcance'], description: 'Empurra você e inimigo em direções opostas.' },
  265: { id: 265, name: 'infused_raindrop', displayName: 'Infused Raindrop', image: `${ITEM_BASE_URL}/infused_raindrop.png`, cost: 225 },
  267: { id: 267, name: 'spirit_vessel', displayName: 'Spirit Vessel', image: `${ITEM_BASE_URL}/spirit_vessel.png`, cost: 2725 },
  269: { id: 269, name: 'holy_locket', displayName: 'Holy Locket', image: `${ITEM_BASE_URL}/holy_locket.png`, cost: 2250 },
  271: { id: 271, name: 'ultimate_scepter_2', displayName: 'Ultimate Scepter 2', image: `${ITEM_BASE_URL}/ultimate_scepter_2.png`, cost: 5800 },
  273: { id: 273, name: 'kaya_and_sange', displayName: 'Kaya And Sange', image: `${ITEM_BASE_URL}/kaya_and_sange.png`, cost: 4200, stats: ['+16 Força/Inteligência', '+16 Amplificação Spell'], description: 'Reduz dano, aumenta spell damage e lifesteal.' },
  276: { id: 276, name: 'combo_breaker', displayName: 'Combo Breaker', image: `${ITEM_BASE_URL}/combo_breaker.png` },
  277: { id: 277, name: 'yasha_and_kaya', displayName: 'Yasha And Kaya', image: `${ITEM_BASE_URL}/yasha_and_kaya.png`, cost: 4200, stats: ['+16 Agilidade/Inteligência', '+16% Velocidade'], description: 'Aumenta velocidade, spell damage e mana cost reduction.' },
  279: { id: 279, name: 'ring_of_tarrasque', displayName: 'Ring Of Tarrasque', image: `${ITEM_BASE_URL}/ring_of_tarrasque.png`, cost: 1800 },
  286: { id: 286, name: 'flying_courier', displayName: 'Flying Courier', image: `${ITEM_BASE_URL}/flying_courier.png`, cost: 100 },
  287: { id: 287, name: 'keen_optic', displayName: 'Keen Optic', image: `${ITEM_BASE_URL}/keen_optic.png` },
  288: { id: 288, name: 'grove_bow', displayName: 'Grove Bow', image: `${ITEM_BASE_URL}/grove_bow.png` },
  289: { id: 289, name: 'quickening_charm', displayName: 'Quickening Charm', image: `${ITEM_BASE_URL}/quickening_charm.png` },
  290: { id: 290, name: 'philosophers_stone', displayName: 'Philosophers Stone', image: `${ITEM_BASE_URL}/philosophers_stone.png` },
  291: { id: 291, name: 'force_boots', displayName: 'Force Boots', image: `${ITEM_BASE_URL}/force_boots.png` },
  292: { id: 292, name: 'desolator_2', displayName: 'Desolator 2', image: `${ITEM_BASE_URL}/desolator_2.png` },
  293: { id: 293, name: 'phoenix_ash', displayName: 'Phoenix Ash', image: `${ITEM_BASE_URL}/phoenix_ash.png` },
  294: { id: 294, name: 'seer_stone', displayName: 'Seer Stone', image: `${ITEM_BASE_URL}/seer_stone.png` },
  295: { id: 295, name: 'greater_mango', displayName: 'Greater Mango', image: `${ITEM_BASE_URL}/greater_mango.png` },
  297: { id: 297, name: 'vampire_fangs', displayName: 'Vampire Fangs', image: `${ITEM_BASE_URL}/vampire_fangs.png` },
  298: { id: 298, name: 'craggy_coat', displayName: 'Craggy Coat', image: `${ITEM_BASE_URL}/craggy_coat.png` },
  299: { id: 299, name: 'greater_faerie_fire', displayName: 'Greater Faerie Fire', image: `${ITEM_BASE_URL}/greater_faerie_fire.png` },
  300: { id: 300, name: 'timeless_relic', displayName: 'Timeless Relic', image: `${ITEM_BASE_URL}/timeless_relic.png` },
  301: { id: 301, name: 'mirror_shield', displayName: 'Mirror Shield', image: `${ITEM_BASE_URL}/mirror_shield.png` },
  302: { id: 302, name: 'elixer', displayName: 'Elixer', image: `${ITEM_BASE_URL}/elixer.png` },
  304: { id: 304, name: 'ironwood_tree', displayName: 'Ironwood Tree', image: `${ITEM_BASE_URL}/ironwood_tree.png` },
  305: { id: 305, name: 'royal_jelly', displayName: 'Royal Jelly', image: `${ITEM_BASE_URL}/royal_jelly.png` },
  306: { id: 306, name: 'pupils_gift', displayName: 'Pupils Gift', image: `${ITEM_BASE_URL}/pupils_gift.png` },
  307: { id: 307, name: 'tome_of_aghanim', displayName: 'Tome Of Aghanim', image: `${ITEM_BASE_URL}/tome_of_aghanim.png` },
  308: { id: 308, name: 'repair_kit', displayName: 'Repair Kit', image: `${ITEM_BASE_URL}/repair_kit.png` },
  309: { id: 309, name: 'mind_breaker', displayName: 'Mind Breaker', image: `${ITEM_BASE_URL}/mind_breaker.png` },
  310: { id: 310, name: 'third_eye', displayName: 'Third Eye', image: `${ITEM_BASE_URL}/third_eye.png` },
  311: { id: 311, name: 'spell_prism', displayName: 'Spell Prism', image: `${ITEM_BASE_URL}/spell_prism.png` },
  312: { id: 312, name: 'horizon', displayName: 'Horizon', image: `${ITEM_BASE_URL}/horizon.png` },
  313: { id: 313, name: 'fusion_rune', displayName: 'Fusion Rune', image: `${ITEM_BASE_URL}/fusion_rune.png` },
  325: { id: 325, name: 'princes_knife', displayName: 'Princes Knife', image: `${ITEM_BASE_URL}/princes_knife.png` },
  326: { id: 326, name: 'spider_legs', displayName: 'Spider Legs', image: `${ITEM_BASE_URL}/spider_legs.png` },
  0: { id: 0, name: 'unknown', displayName: 'Unknown Item', image: `${ITEM_BASE_URL}/recipe.png` },
};
// Total items: 200


// Função helper para buscar item por ID
export const getItemInfo = (itemId: number): ItemInfo => {
  return ITEMS_MAP[itemId] || ITEMS_MAP[0];
};

// Função helper para buscar item por nome
export const getItemByName = (itemName: string): ItemInfo | undefined => {
  return Object.values(ITEMS_MAP).find(
    item => item.name === itemName || item.displayName === itemName
  );
};

// Exportar lista de todos os items
export const getAllItems = (): ItemInfo[] => {
  return Object.values(ITEMS_MAP);
};
