// Mapeamento completo de itens do Dota 2
// Gerado automaticamente via scripts/generateItemMap.ts
// IDs da API OpenDota
export const ITEM_MAP: { [key: number]: string } = {
  "1": "blink",
  "2": "blades_of_attack",
  "3": "broadsword",
  "4": "chainmail",
  "5": "claymore",
  "6": "helm_of_iron_will",
  "7": "javelin",
  "8": "mithril_hammer",
  "9": "platemail",
  "10": "quarterstaff",
  "11": "quelling_blade",
  "12": "ring_of_protection",
  "13": "gauntlets",
  "14": "slippers",
  "15": "mantle",
  "16": "branches",
  "17": "belt_of_strength",
  "18": "boots_of_elves",
  "19": "robe",
  "20": "circlet",
  "21": "ogre_axe",
  "22": "blade_of_alacrity",
  "23": "staff_of_wizardry",
  "24": "ultimate_orb",
  "25": "gloves",
  "26": "lifesteal",
  "27": "ring_of_regen",
  "28": "sobi_mask",
  "29": "boots",
  "30": "gem",
  "31": "cloak",
  "32": "talisman_of_evasion",
  "33": "cheese",
  "34": "magic_stick",
  "36": "magic_wand",
  "37": "ghost",
  "38": "clarity",
  "39": "flask",
  "40": "dust",
  "41": "bottle",
  "42": "ward_observer",
  "43": "ward_sentry",
  "44": "tango",
  "45": "courier",
  "46": "tpscroll",
  "48": "travel_boots",
  "50": "phase_boots",
  "51": "demon_edge",
  "52": "eagle",
  "53": "reaver",
  "54": "relic",
  "55": "hyperstone",
  "56": "ring_of_health",
  "57": "void_stone",
  "58": "mystic_staff",
  "59": "energy_booster",
  "60": "point_booster",
  "61": "vitality_booster",
  "63": "power_treads",
  "65": "hand_of_midas",
  "67": "oblivion_staff",
  "69": "pers",
  "71": "poor_mans_shield",
  "73": "bracer",
  "75": "wraith_band",
  "77": "null_talisman",
  "79": "mekansm",
  "81": "vladmir",
  "86": "buckler",
  "88": "ring_of_basilius",
  "90": "pipe",
  "92": "urn_of_shadows",
  "94": "headdress",
  "96": "sheepstick",
  "98": "orchid",
  "100": "cyclone",
  "102": "force_staff",
  "104": "dagon",
  "106": "necronomicon",
  "108": "ultimate_scepter",
  "110": "refresher",
  "112": "assault",
  "114": "heart",
  "116": "black_king_bar",
  "117": "aegis",
  "119": "shivas_guard",
  "121": "bloodstone",
  "123": "sphere",
  "125": "vanguard",
  "127": "blade_mail",
  "129": "soul_booster",
  "131": "hood_of_defiance",
  "133": "rapier",
  "135": "monkey_king_bar",
  "137": "radiance",
  "139": "butterfly",
  "141": "greater_crit",
  "143": "basher",
  "145": "bfury",
  "147": "manta",
  "149": "lesser_crit",
  "151": "armlet",
  "152": "invis_sword",
  "154": "sange_and_yasha",
  "156": "satanic",
  "158": "mjollnir",
  "160": "skadi",
  "162": "sange",
  "164": "helm_of_the_dominator",
  "166": "maelstrom",
  "168": "desolator",
  "170": "yasha",
  "172": "mask_of_madness",
  "174": "diffusal_blade",
  "176": "ethereal_blade",
  "178": "soul_ring",
  "180": "arcane_boots",
  "181": "orb_of_venom",
  "182": "stout_shield",
  "185": "ancient_janggo",
  "187": "medallion_of_courage",
  "188": "smoke_of_deceit",
  "190": "veil_of_discord",
  "193": "necronomicon_2",
  "194": "necronomicon_3",
  "196": "diffusal_blade_2",
  "201": "dagon_2",
  "202": "dagon_3",
  "203": "dagon_4",
  "204": "dagon_5",
  "206": "rod_of_atos",
  "208": "abyssal_blade",
  "210": "heavens_halberd",
  "212": "ring_of_aquila",
  "214": "tranquil_boots",
  "215": "shadow_amulet",
  "216": "enchanted_mango",
  "218": "ward_dispenser",
  "220": "travel_boots_2",
  "223": "meteor_hammer",
  "225": "nullifier",
  "226": "lotus_orb",
  "229": "solar_crest",
  "231": "guardian_greaves",
  "232": "aether_lens",
  "235": "octarine_core",
  "236": "dragon_lance",
  "237": "faerie_fire",
  "239": "iron_talon",
  "240": "blight_stone",
  "241": "tango_single",
  "242": "crimson_guard",
  "244": "wind_lace",
  "247": "moon_shard",
  "249": "silver_edge",
  "250": "bloodthorn",
  "252": "echo_sabre",
  "254": "glimmer_cape",
  "256": "aeon_disk",
  "257": "tome_of_knowledge",
  "259": "kaya",
  "260": "refresher_shard",
  "261": "crown",
  "263": "hurricane_pike",
  "265": "infused_raindrop",
  "267": "spirit_vessel",
  "269": "holy_locket",
  "271": "ultimate_scepter_2",
  "273": "kaya_and_sange",
  "277": "yasha_and_kaya",
  "279": "ring_of_tarrasque",
  "286": "flying_courier",
  "287": "keen_optic",
  "288": "grove_bow",
  "289": "quickening_charm",
  "290": "philosophers_stone",
  "291": "force_boots",
  "292": "desolator_2",
  "293": "phoenix_ash",
  "294": "seer_stone",
  "297": "vampire_fangs",
  "298": "craggy_coat",
  "299": "greater_faerie_fire",
  "300": "timeless_relic",
  "301": "mirror_shield",
  "302": "elixer",
  "304": "ironwood_tree",
  "305": "royal_jelly",
  "306": "pupils_gift",
  "307": "tome_of_aghanim",
  "308": "repair_kit",
  "309": "mind_breaker",
  "310": "third_eye",
  "311": "spell_prism",
  "313": "fusion_rune",
  "325": "princes_knife",
  "326": "spider_legs",
  "327": "helm_of_the_undying",
  "328": "mango_tree",
  "330": "witless_shako",
  "331": "vambrace",
  "334": "imp_claw",
  "335": "flicker",
  "336": "spy_gadget",
  "349": "arcane_ring",
  "354": "ocean_heart",
  "355": "broom_handle",
  "356": "trusty_shovel",
  "357": "nether_shawl",
  "358": "dragon_scale",
  "359": "essence_ring",
  "360": "clumsy_net",
  "361": "enchanted_quiver",
  "362": "ninja_gear",
  "363": "illusionsts_cape",
  "364": "havoc_hammer",
  "365": "panic_button",
  "366": "apex",
  "367": "ballista",
  "368": "woodland_striders",
  "369": "trident",
  "370": "demonicon",
  "371": "fallen_sky",
  "372": "pirate_hat",
  "374": "ex_machina",
  "375": "faded_broach",
  "376": "paladin_sword",
  "377": "minotaur_horn",
  "378": "orb_of_destruction",
  "379": "the_leveller",
  "381": "titan_sliver",
  "473": "voodoo_mask",
  "485": "blitz_knuckles",
  "534": "witch_blade",
  "565": "chipped_vest",
  "569": "orb_of_corrosion",
  "571": "trickster_cloak",
  "573": "elven_tunic",
  "574": "cloak_of_flames",
  "577": "possessed_mask",
  "585": "stormcrafter",
  "589": "mysterious_hat",
  "593": "fluffy_hat",
  "596": "falcon_blade",
  "598": "mage_slayer",
  "600": "overwhelming_blink",
  "603": "swift_blink",
  "604": "arcane_blink",
  "609": "aghanims_shard",
  "610": "wind_waker",
  "635": "helm_of_the_overlord",
  "638": "penta_edged_sword",
  "675": "psychic_headband",
  "676": "ceremonial_robe",
  "677": "book_of_shadows",
  "678": "giants_ring",
  "679": "vengeances_shadow",
  "680": "bullwhip",
  "686": "quicksilver_amulet",
  "692": "eternal_shroud",
  "725": "aghanims_shard_roshan",
  "727": "ultimate_scepter_roshan",
  "825": "ascetic_cap",
  "828": "misericorde",
  "829": "force_field",
  "834": "black_powder_bag",
  "835": "paintball",
  "837": "heavy_blade",
  "838": "unstable_wand",
  "840": "pogo_stick",
  "908": "wraith_pact",
  "911": "revenants_brooch",
  "931": "boots_of_bearing",
  "939": "harpoon",
  "945": "seeds_of_serenity",
  "946": "lance_of_pursuit",
  "947": "occult_bracelet",
  "949": "ogre_seal_totem",
  "950": "defiant_shell",
  "990": "eye_of_the_vizier",
  "1021": "river_painter",
  "1022": "river_painter2",
  "1023": "river_painter3",
  "1024": "river_painter4",
  "1025": "river_painter5",
  "1026": "river_painter6",
  "1027": "river_painter7",
  "1028": "mutation_tombstone",
  "1030": "pocket_tower",
  "1032": "pocket_roshan",
  "1076": "specialists_array",
  "1077": "dagger_of_ristul",
  "1090": "muertas_gun",
  "1095": "lunar_crest",
  "1097": "disperser",
  "1107": "phylactery",
  "1122": "diadem",
  "1123": "blood_grenade",
  "1124": "spark_of_courage",
  "1125": "cornucopia",
  "1128": "pavise",
  "1154": "royale_with_cheese",
  "1156": "ancient_guardian",
  "1157": "safety_bubble",
  "1158": "whisper_of_the_dread",
  "1159": "nemesis_curse",
  "1160": "avianas_feather",
  "1161": "unwavering_condition",
  "1167": "light_collector",
  "1168": "rattlecage",
  "1440": "black_grimoire",
  "1441": "grisgris",
  "1466": "gungir",
  "1575": "orb_of_frost",
  "1576": "enhancement_vast",
  "1577": "enhancement_quickened",
  "1578": "cursed_circlet",
  "1579": "ogre_heart",
  "1580": "neutral_tabi",
  "1581": "enhancement_audacious",
  "1583": "enhancement_mystical",
  "1584": "enhancement_alert",
  "1585": "enhancement_brawny",
  "1586": "enhancement_tough",
  "1587": "enhancement_feverish",
  "1588": "enhancement_fleetfooted",
  "1589": "enhancement_crude",
  "1590": "enhancement_boundless",
  "1591": "enhancement_wise",
  "1592": "enhancement_timeless",
  "1593": "enhancement_greedy",
  "1594": "enhancement_vampiric",
  "1595": "enhancement_keen_eyed",
  "1596": "enhancement_evolved",
  "1597": "enhancement_titanic",
  "1598": "unrelenting_eye",
  "1599": "mana_draught",
  "1600": "rippers_lash",
  "1601": "crippling_crossbow",
  "1602": "gale_guard",
  "1603": "gunpowder_gauntlets",
  "1604": "searing_signet",
  "1605": "serrated_shiv",
  "1606": "polliwog_charm",
  "1607": "magnifying_monocle",
  "1608": "pyrrhic_cloak",
  "1609": "madstone_bundle",
  "1636": "crystal_raindrop",
  "1637": "kobold_cup",
  "1638": "dormant_curio",
  "1639": "sisters_shroud",
  "1640": "jidi_pollen_bag",
  "1641": "outworld_staff",
  "1642": "dezun_bloodrite",
  "1643": "giant_maul",
  "1644": "divine_regalia",
  "1645": "divine_regalia_broken",
  "1646": "circlet_of_the_flayed_twins",
  "1647": "enhancement_fierce",
  "1648": "enhancement_dominant",
  "1649": "enhancement_restorative",
  "1650": "enhancement_thick",
  "1651": "enhancement_curious",
  "1652": "furion_gold_bag",
  "1802": "tiara_of_selemene",
  "1803": "doubloon",
  "1804": "roshans_banner",
  "1806": "devastator",
  "1808": "angels_demise",
  "2091": "tier1_token",
  "2092": "tier2_token",
  "2093": "tier3_token",
  "2094": "tier4_token",
  "2095": "tier5_token",
  "2096": "vindicators_axe",
  "2097": "duelist_gloves",
  "2190": "dandelion_amulet",
  "2192": "martyrs_plate",
  "2193": "gossamer_cape",
  "4204": "famango",
  "4205": "great_famango",
  "4206": "greater_famango",
  "4300": "ofrenda",
  "4301": "ofrenda_shovel",
  "4302": "ofrenda_pledge"
};

export const ITEM_NAMES: { [key: string]: string } = {
  "blink": "Blink Dagger",
  "blades_of_attack": "Blades of Attack",
  "broadsword": "Broadsword",
  "chainmail": "Chainmail",
  "claymore": "Claymore",
  "helm_of_iron_will": "Helm of Iron Will",
  "javelin": "Javelin",
  "mithril_hammer": "Mithril Hammer",
  "platemail": "Platemail",
  "quarterstaff": "Quarterstaff",
  "quelling_blade": "Quelling Blade",
  "ring_of_protection": "Ring of Protection",
  "gauntlets": "Gauntlets of Strength",
  "slippers": "Slippers of Agility",
  "mantle": "Mantle of Intelligence",
  "branches": "Iron Branch",
  "belt_of_strength": "Belt of Strength",
  "boots_of_elves": "Band of Elvenskin",
  "robe": "Robe of the Magi",
  "circlet": "Circlet",
  "ogre_axe": "Ogre Axe",
  "blade_of_alacrity": "Blade of Alacrity",
  "staff_of_wizardry": "Staff of Wizardry",
  "ultimate_orb": "Ultimate Orb",
  "gloves": "Gloves of Haste",
  "lifesteal": "Morbid Mask",
  "ring_of_regen": "Ring of Regen",
  "sobi_mask": "Sage's Mask",
  "boots": "Boots of Speed",
  "gem": "Gem of True Sight",
  "cloak": "Cloak",
  "talisman_of_evasion": "Talisman of Evasion",
  "cheese": "Cheese",
  "magic_stick": "Magic Stick",
  "magic_wand": "Magic Wand",
  "ghost": "Ghost Scepter",
  "clarity": "Clarity",
  "flask": "Healing Salve",
  "dust": "Dust of Appearance",
  "bottle": "Bottle",
  "ward_observer": "Observer Ward",
  "ward_sentry": "Sentry Ward",
  "tango": "Tango",
  "courier": "Animal Courier",
  "tpscroll": "Town Portal Scroll",
  "travel_boots": "Boots of Travel",
  "phase_boots": "Phase Boots",
  "demon_edge": "Demon Edge",
  "eagle": "Eaglesong",
  "reaver": "Reaver",
  "relic": "Sacred Relic",
  "hyperstone": "Hyperstone",
  "ring_of_health": "Ring of Health",
  "void_stone": "Void Stone",
  "mystic_staff": "Mystic Staff",
  "energy_booster": "Energy Booster",
  "point_booster": "Point Booster",
  "vitality_booster": "Vitality Booster",
  "power_treads": "Power Treads",
  "hand_of_midas": "Hand of Midas",
  "oblivion_staff": "Oblivion Staff",
  "pers": "Perseverance",
  "poor_mans_shield": "Poor Man's Shield",
  "bracer": "Bracer",
  "wraith_band": "Wraith Band",
  "null_talisman": "Null Talisman",
  "mekansm": "Mekansm",
  "vladmir": "Vladmir's Offering",
  "buckler": "Buckler",
  "ring_of_basilius": "Ring of Basilius",
  "pipe": "Pipe of Insight",
  "urn_of_shadows": "Urn of Shadows",
  "headdress": "Headdress",
  "sheepstick": "Scythe of Vyse",
  "orchid": "Orchid Malevolence",
  "cyclone": "Eul's Scepter of Divinity",
  "force_staff": "Force Staff",
  "dagon": "Dagon",
  "necronomicon": "Necronomicon",
  "ultimate_scepter": "Aghanim's Scepter",
  "refresher": "Refresher Orb",
  "assault": "Assault Cuirass",
  "heart": "Heart of Tarrasque",
  "black_king_bar": "Black King Bar",
  "aegis": "Aegis of the Immortal",
  "shivas_guard": "Shiva's Guard",
  "bloodstone": "Bloodstone",
  "sphere": "Linken's Sphere",
  "vanguard": "Vanguard",
  "blade_mail": "Blade Mail",
  "soul_booster": "Soul Booster",
  "hood_of_defiance": "Hood of Defiance",
  "rapier": "Divine Rapier",
  "monkey_king_bar": "Monkey King Bar",
  "radiance": "Radiance",
  "butterfly": "Butterfly",
  "greater_crit": "Daedalus",
  "basher": "Skull Basher",
  "bfury": "Battle Fury",
  "manta": "Manta Style",
  "lesser_crit": "Crystalys",
  "armlet": "Armlet of Mordiggian",
  "invis_sword": "Shadow Blade",
  "sange_and_yasha": "Sange and Yasha",
  "satanic": "Satanic",
  "mjollnir": "Mjollnir",
  "skadi": "Eye of Skadi",
  "sange": "Sange",
  "helm_of_the_dominator": "Helm of the Dominator",
  "maelstrom": "Maelstrom",
  "desolator": "Desolator",
  "yasha": "Yasha",
  "mask_of_madness": "Mask of Madness",
  "diffusal_blade": "Diffusal Blade",
  "ethereal_blade": "Ethereal Blade",
  "soul_ring": "Soul Ring",
  "arcane_boots": "Arcane Boots",
  "orb_of_venom": "Orb of Venom",
  "stout_shield": "Stout Shield",
  "ancient_janggo": "Drum of Endurance",
  "medallion_of_courage": "Medallion of Courage",
  "smoke_of_deceit": "Smoke of Deceit",
  "veil_of_discord": "Veil of Discord",
  "necronomicon_2": "Necronomicon",
  "necronomicon_3": "Necronomicon",
  "diffusal_blade_2": "Diffusal Blade",
  "dagon_2": "Dagon",
  "dagon_3": "Dagon",
  "dagon_4": "Dagon",
  "dagon_5": "Dagon",
  "rod_of_atos": "Rod of Atos",
  "abyssal_blade": "Abyssal Blade",
  "heavens_halberd": "Heaven's Halberd",
  "ring_of_aquila": "Ring of Aquila",
  "tranquil_boots": "Tranquil Boots",
  "shadow_amulet": "Shadow Amulet",
  "enchanted_mango": "Enchanted Mango",
  "ward_dispenser": "Observer and Sentry Wards",
  "travel_boots_2": "Boots of Travel 2",
  "meteor_hammer": "Meteor Hammer",
  "nullifier": "Nullifier",
  "lotus_orb": "Lotus Orb",
  "solar_crest": "Solar Crest",
  "guardian_greaves": "Guardian Greaves",
  "aether_lens": "Aether Lens",
  "octarine_core": "Octarine Core",
  "dragon_lance": "Dragon Lance",
  "faerie_fire": "Faerie Fire",
  "iron_talon": "Iron Talon",
  "blight_stone": "Orb of Blight",
  "tango_single": "Tango (Shared)",
  "crimson_guard": "Crimson Guard",
  "wind_lace": "Wind Lace",
  "moon_shard": "Moon Shard",
  "silver_edge": "Silver Edge",
  "bloodthorn": "Bloodthorn",
  "echo_sabre": "Echo Sabre",
  "glimmer_cape": "Glimmer Cape",
  "aeon_disk": "Aeon Disk",
  "tome_of_knowledge": "Tome of Knowledge",
  "kaya": "Kaya",
  "refresher_shard": "Refresher Shard",
  "crown": "Crown",
  "hurricane_pike": "Hurricane Pike",
  "infused_raindrop": "Infused Raindrops",
  "spirit_vessel": "Spirit Vessel",
  "holy_locket": "Holy Locket",
  "ultimate_scepter_2": "Aghanim's Blessing",
  "kaya_and_sange": "Kaya and Sange",
  "yasha_and_kaya": "Yasha and Kaya",
  "ring_of_tarrasque": "Ring of Tarrasque",
  "flying_courier": "Flying Courier",
  "keen_optic": "Keen Optic",
  "grove_bow": "Grove Bow",
  "quickening_charm": "Quickening Charm",
  "philosophers_stone": "Philosopher's Stone",
  "force_boots": "Force Boots",
  "desolator_2": "Stygian Desolator",
  "phoenix_ash": "Phoenix Ash",
  "seer_stone": "Seer Stone",
  "vampire_fangs": "Vampire Fangs",
  "craggy_coat": "Craggy Coat",
  "greater_faerie_fire": "Greater Faerie Fire",
  "timeless_relic": "Timeless Relic",
  "mirror_shield": "Mirror Shield",
  "elixer": "Elixir",
  "ironwood_tree": "Ironwood Tree",
  "royal_jelly": "Royal Jelly",
  "pupils_gift": "Pupil's Gift",
  "tome_of_aghanim": "Tome of Aghanim",
  "repair_kit": "Repair Kit",
  "mind_breaker": "Mind Breaker",
  "third_eye": "Third Eye",
  "spell_prism": "Spell Prism",
  "fusion_rune": "Fusion Rune",
  "princes_knife": "Prince's Knife",
  "spider_legs": "Spider Legs",
  "helm_of_the_undying": "Helm of the Undying",
  "mango_tree": "Mango Tree",
  "witless_shako": "Witless Shako",
  "vambrace": "Vambrace",
  "imp_claw": "Imp Claw",
  "flicker": "Flicker",
  "spy_gadget": "Telescope",
  "arcane_ring": "Arcane Ring",
  "ocean_heart": "Ocean Heart",
  "broom_handle": "Broom Handle",
  "trusty_shovel": "Trusty Shovel",
  "nether_shawl": "Nether Shawl",
  "dragon_scale": "Dragon Scale",
  "essence_ring": "Essence Ring",
  "clumsy_net": "Clumsy Net",
  "enchanted_quiver": "Enchanted Quiver",
  "ninja_gear": "Ninja Gear",
  "illusionsts_cape": "Illusionist's Cape",
  "havoc_hammer": "Havoc Hammer",
  "panic_button": "Magic Lamp",
  "apex": "Apex",
  "ballista": "Ballista",
  "woodland_striders": "Woodland Striders",
  "trident": "Trident",
  "demonicon": "Book of the Dead",
  "fallen_sky": "Fallen Sky",
  "pirate_hat": "Pirate Hat",
  "ex_machina": "Ex Machina",
  "faded_broach": "Faded Broach",
  "paladin_sword": "Paladin Sword",
  "minotaur_horn": "Minotaur Horn",
  "orb_of_destruction": "Orb of Destruction",
  "the_leveller": "The Leveller",
  "titan_sliver": "Titan Sliver",
  "voodoo_mask": "Voodoo Mask",
  "blitz_knuckles": "Blitz Knuckles",
  "witch_blade": "Witch Blade",
  "chipped_vest": "Chipped Vest",
  "orb_of_corrosion": "Orb of Corrosion",
  "trickster_cloak": "Trickster Cloak",
  "elven_tunic": "Elven Tunic",
  "cloak_of_flames": "Cloak of Flames",
  "possessed_mask": "Possessed Mask",
  "stormcrafter": "Stormcrafter",
  "mysterious_hat": "Fairy's Trinket",
  "fluffy_hat": "Fluffy Hat",
  "falcon_blade": "Falcon Blade",
  "mage_slayer": "Mage Slayer",
  "overwhelming_blink": "Overwhelming Blink",
  "swift_blink": "Swift Blink",
  "arcane_blink": "Arcane Blink",
  "aghanims_shard": "Aghanim's Shard",
  "wind_waker": "Wind Waker",
  "helm_of_the_overlord": "Helm of the Overlord",
  "penta_edged_sword": "Penta-Edged Sword",
  "psychic_headband": "Psychic Headband",
  "ceremonial_robe": "Ceremonial Robe",
  "book_of_shadows": "Book of Shadows",
  "giants_ring": "Giant's Ring",
  "vengeances_shadow": "Shadow of Vengeance",
  "bullwhip": "Bullwhip",
  "quicksilver_amulet": "Quicksilver Amulet",
  "eternal_shroud": "Eternal Shroud",
  "aghanims_shard_roshan": "Aghanim's Shard - Consumable",
  "ultimate_scepter_roshan": "Aghanim's Blessing - Roshan",
  "ascetic_cap": "Ascetic's Cap",
  "misericorde": "Brigand's Blade",
  "force_field": "Arcanist's Armor",
  "black_powder_bag": "Blast Rig",
  "paintball": "Fae Grenade",
  "heavy_blade": "Witchbane",
  "unstable_wand": "Pig Pole",
  "pogo_stick": "Tumbler's Toy",
  "wraith_pact": "Wraith Pact",
  "revenants_brooch": "Revenant's Brooch",
  "boots_of_bearing": "Boots of Bearing",
  "harpoon": "Harpoon",
  "seeds_of_serenity": "Seeds of Serenity",
  "lance_of_pursuit": "Lance of Pursuit",
  "occult_bracelet": "Occult Bracelet",
  "ogre_seal_totem": "Ogre Seal Totem",
  "defiant_shell": "Defiant Shell",
  "eye_of_the_vizier": "Eye of the Vizier",
  "river_painter": "River Vial: Chrome",
  "river_painter2": "River Vial: Dry",
  "river_painter3": "River Vial: Slime",
  "river_painter4": "River Vial: Oil",
  "river_painter5": "River Vial: Electrified",
  "river_painter6": "River Vial: Potion",
  "river_painter7": "River Vial: Blood",
  "mutation_tombstone": "Tombstone",
  "pocket_tower": "Pocket Tower",
  "pocket_roshan": "Pocket Roshan",
  "specialists_array": "Specialist's Array",
  "dagger_of_ristul": "Dagger of Ristul",
  "muertas_gun": "Mercy & Grace",
  "lunar_crest": "Lunar Crest",
  "disperser": "Disperser",
  "phylactery": "Phylactery",
  "diadem": "Diadem",
  "blood_grenade": "Blood Grenade",
  "spark_of_courage": "Spark of Courage",
  "cornucopia": "Cornucopia",
  "pavise": "Pavise",
  "royale_with_cheese": "Block of Cheese",
  "ancient_guardian": "Ancient Guardian",
  "safety_bubble": "Safety Bubble",
  "whisper_of_the_dread": "Whisper of the Dread",
  "nemesis_curse": "Nemesis Curse",
  "avianas_feather": "Aviana's Feather",
  "unwavering_condition": "Unwavering Condition",
  "light_collector": "Light Collector",
  "rattlecage": "Rattlecage",
  "black_grimoire": "Black Grimoire",
  "grisgris": "Gris-Gris",
  "gungir": "Gleipnir",
  "orb_of_frost": "Orb of Frost",
  "enhancement_vast": "Vast",
  "enhancement_quickened": "Quickened",
  "cursed_circlet": "Accursed",
  "ogre_heart": "Restorative",
  "neutral_tabi": "Elusive",
  "enhancement_audacious": "Audacious",
  "enhancement_mystical": "Mystical",
  "enhancement_alert": "Alert",
  "enhancement_brawny": "Brawny",
  "enhancement_tough": "Tough",
  "enhancement_feverish": "Feverish",
  "enhancement_fleetfooted": "Fleetfooted",
  "enhancement_crude": "Crude",
  "enhancement_boundless": "Boundless",
  "enhancement_wise": "Wise",
  "enhancement_timeless": "Timeless",
  "enhancement_greedy": "Greedy",
  "enhancement_vampiric": "Vampiric",
  "enhancement_keen_eyed": "Keen-eyed",
  "enhancement_evolved": "Evolved",
  "enhancement_titanic": "Titanic",
  "unrelenting_eye": "Unrelenting Eye",
  "mana_draught": "Mana Draught",
  "rippers_lash": "Ripper's Lash",
  "crippling_crossbow": "Crippling Crossbow",
  "gale_guard": "Gale Guard",
  "gunpowder_gauntlets": "Gunpowder Gauntlet",
  "searing_signet": "Searing Signet",
  "serrated_shiv": "Serrated Shiv",
  "polliwog_charm": "Pollywog Charm",
  "magnifying_monocle": "Magnifying Monocle",
  "pyrrhic_cloak": "Pyrrhic Cloak",
  "madstone_bundle": "Madstone Bundle",
  "crystal_raindrop": "Crystal Raindrop",
  "kobold_cup": "Kobold Cup",
  "dormant_curio": "Dormant Curio",
  "sisters_shroud": "Sister's Shroud",
  "jidi_pollen_bag": "Jidi Pollen Bag",
  "outworld_staff": "Outworld Staff",
  "dezun_bloodrite": "Dezun Bloodrite",
  "giant_maul": "Giant's Maul",
  "divine_regalia": "Divine Regalia",
  "divine_regalia_broken": "Disgraced Regalia",
  "circlet_of_the_flayed_twins": "Circlet of the Flayed Twins",
  "enhancement_fierce": "Fierce",
  "enhancement_dominant": "Dominant",
  "enhancement_restorative": "Restorative",
  "enhancement_thick": "Thick",
  "enhancement_curious": "Unleashed",
  "furion_gold_bag": "Bag of Gold",
  "tiara_of_selemene": "Tiara of Selemene",
  "doubloon": "Doubloon",
  "roshans_banner": "Roshan's Banner",
  "devastator": "Parasma",
  "angels_demise": "Khanda",
  "tier1_token": "Tier 1 Token",
  "tier2_token": "Tier 2 Token",
  "tier3_token": "Tier 3 Token",
  "tier4_token": "Tier 4 Token",
  "tier5_token": "Tier 5 Token",
  "vindicators_axe": "Vindicator's Axe",
  "duelist_gloves": "Duelist Gloves",
  "dandelion_amulet": "Dandelion Amulet",
  "martyrs_plate": "Martyr's Plate",
  "gossamer_cape": "Gossamer Cape",
  "famango": "Healing Lotus",
  "great_famango": "Great Healing Lotus",
  "greater_famango": "Greater Healing Lotus",
  "ofrenda": "Beloved Memory",
  "ofrenda_shovel": "Scrying Shovel",
  "ofrenda_pledge": "Forebearer's Fortune"
};

// Tags de itens para lógica situacional
export interface ItemTags {
  armorReduction?: boolean;
  silence?: boolean;
  dispel?: boolean;
  magicImmunity?: boolean;
  mobility?: boolean;
  damage?: boolean;
  survival?: boolean;
  heal?: boolean;
  manaRegen?: boolean;
  disableEvasion?: boolean;
}

export const ITEM_TAGS: { [itemName: string]: ItemTags } = {
  black_king_bar: { magicImmunity: true, survival: true },
  sphere: { survival: true },
  blink: { mobility: true },
  silver_edge: { mobility: true, damage: true },
  orchid: { silence: true, damage: true },
  bloodthorn: { silence: true, damage: true, disableEvasion: true },
  nullifier: { dispel: true },
  mask_of_madness: { damage: true },
  assault: { armorReduction: true, damage: true },
  desolator: { armorReduction: true, damage: true },
  solar_crest: { armorReduction: true },
  shivas_guard: { armorReduction: true },
  heart: { survival: true, heal: true },
  satanic: { survival: true, heal: true },
  mjollnir: { damage: true },
  daedalus: { damage: true },
  monkey_king_bar: { damage: true, disableEvasion: true },
  overwhelming_blink: { mobility: true, damage: true },
  swift_blink: { mobility: true, damage: true },
  arcane_blink: { mobility: true, manaRegen: true },
  manta: { dispel: true, damage: true },
  lotus_orb: { dispel: true, survival: true },
  euls: { dispel: true },
  pipe: { survival: true },
  crimson_guard: { survival: true },
  blade_mail: { survival: true },
};

export function getItemName(itemId: number): string {
  const key = ITEM_MAP[itemId];
  return key ? ITEM_NAMES[key] || key : `item_${itemId}`;
}
