name: Tests

on:
  push:
    branches: [main, master, feature/**]
  pull_request:
    branches: [main, master]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm run setup

      - name: Run backend unit tests
        run: npm run test:backend
        env:
          CI: true
          NODE_ENV: test

      - name: Run frontend unit tests
        run: cd frontend && npm test -- --run
        env:
          CI: true
          NODE_ENV: test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm run setup

      - name: Lint frontend
        run: cd frontend && npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm run setup

      - name: Build backend
        run: npm run build:backend

      - name: Build frontend
        run: npm run build:frontend
